# Generated by Django 3.0.8 on 2020-07-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogpost',
        ),
    ]
